project:
  type: book
  
toc-depth: 2

book:
  title: "bayescogsci exercises"
  author: "surtich@gmail.com"
  chapters:
    - index.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false

  pdf:
    documentclass: scrreprt



